name: Rolling Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Release Go Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Binaries
        run: make build


      - name: Create Release and Upload Assets
        run: |
          release_id=$(gh release create rolling-release ./bin/sudoku_darwin_amd64 ./bin/sudoku_darwin_arm64 ./bin/sudoku_linux_amd64 ./bin/sudoku_linux_arm64 ./bin/sudoku_windows_amd64.exe ./bin/sudoku_windows_arm64.exe --title "Rolling Release" --notes "Automated release.")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
